name: felsi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.1
  flutter_svg: ^2.0.16
  logger: ^2.5.0
  shared_preferences: ^2.3.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  custom_lint:
  riverpod_generator:
  riverpod_lint:
  flutter_gen_runner:

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/logo/
    - assets/icons/

flutter_gen:
  output: lib/src/core/gen
  line_length: 80

  integrations:
    flutter_svg: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
